config/routes.rb
PhotoBlog::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions
  resources :users

  resources :posts

  post 'posts/new_comment' => 'posts#new_comment', as: :new_comment

  root 'users#index'

end

app/models/comment.rb
class Comment
	include Mongoid::Document

	field :author, type: String
	field :comment, type: String

	embedded_in :post
end

app/models/photo.rb
# class Photo
#     include Mongoid::Document
#     include Mongoid::Paperclip

#     field :date, type: DateTime

#     belongs_to :post
#     has_mongoid_attached_file :image, 
#    :styles => {
#       :original => ['1920x1680>', :jpg],
#       :small    => ['100x100#',   :jpg],
#       :medium   => ['250x250',    :jpg],
#       :large    => ['500x500>',   :jpg]
#     }
#     validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
# end

app/models/post.rb
class Post
  include Mongoid::Document
  field :title, type: String
  field :camera, type: String
  field :desc, type: String

  embeds_many :comments
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :email, type: String
  field :password_digest, type: String

  has_secure_password

  # attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	 before_filter :authorize

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/photos_controller.rb
# class PhotosController < ApplicationController
#   def index
#     @photos = Photo.all
#   end
#   def new
#     @photo =Photo.new
#   end
#   def create
#     # Find our parent decision that we should attach to
#     @photo = posts.photos.new(photo_params)
#     @photo.date ||= DateTime.now
#     # Attach this criterion to a decision
#     if @photo.save
#       redirect_to post_path
#     else
#       render 'new'
#     end
#   end

#   def show

#   end

#   def photo_params
#     params.require(:photo).permit(:image)
#   end
# end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])

    # adding in comments on show page
    @comment = Comment.new
	end

	def new
		@post = Post.new
	end

  def create
		@post = Post.new(params.require(:post).permit(:title, :camera, :desc))
		if @post.save
				redirect_to posts_path
		else
				render 'new'
		end
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update_attributes(params.require(:post).permit(:title, :camera, :desc))
  		redirect_to post_path
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
  	redirect_to posts_path
  end

  # new comment 
  def new_comment
    @id = params[:post_id]
    @post = Post.find(@id)
    @post.comments << Comment.new(params.require(:comment).permit(:author, :comment))
    if @post.save
      redirect_to post_path(:id => @id)
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :authorize

  def new
  
  end

  def create
    user = User.where(email: params[:email]).first
    # first make sure we actually find a user
    # then see if user authenticates
    if user && user.authenticate(params[:password])
        # sets the cookie to the browser
        session[:user_id] = user.id.to_s
        redirect_to posts_path 
       
    else
        flash.now.alert = "Email or password is invalid"
        render "new"
        # redirect_to new_session_path
    end
  end

  def destroy
    # Kill our cookies!
    reset_session
    redirect_to root_path 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :authorize
	def index

	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end

	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paperclipfun</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!--Bootstrap-->

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
    <!--Authentication-->

    <div id="user_header">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log Out", session_path("current"), method: :delete %>
      <% else %>
        <%= link_to "Sign Up", new_user_path %> or
        <%= link_to "Log In", new_session_path %>
    <% end %>

        <%= yield %>
    </div>  
    
</div>
</body>
</html>

app/views/posts/edit.html.erb
<h1> Edit this Post</h1>

<%= form_for @post do |f| %>
    Title: <%= f.text_field :title %>
    Camera: <%= f.text_field :camera %>
    Description: <%= f.text_field :desc %>

    <%= f.submit "Save Changes" %>

<% end %>

<%= link_to "Back to posts", posts_path %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<ul>
    <% @posts.each do |p| %>
        <li>
            <strong> <%= p.title %> </strong> -- <%= p.camera %> <%= p.desc%> -- <%= link_to "Show", post_path(p) %>
        </li>
    <% end %>
</ul>

<%= link_to "Make a post", new_post_path %>

app/views/posts/new.html.erb
<h1> Enter a new Post</h1>

<%= form_for @post do |f| %>
    Title: <%= f.text_field :title %>
    Camera: <%= f.text_field :camera %>
    Description: <%= f.text_field :desc %>

    <%= f.submit "submit post" %>

<% end %>

<%= link_to "Back to posts", posts_path %>

app/views/posts/show.html.erb
<h1>Title: <%= @post.title %> </h1>
<p><strong>Camera:</strong> Used:<%= @post.camera %></p>
<p><strong>Description:</strong> <%= @post.desc %></p>

<!--added in -->
<%@post.comments.each do |comment| %>

    <div><%=comment.author %></div>
    <div><%=comment.comment %></div>
<% end %>


<%= link_to "Back to posts", posts_path %><br>
<%= link_to "Edit", edit_post_path(@post) %><br>

<%= link_to "Delete this Post!", :post, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %>

<!--Added in -->
<h2>New Comment</h2>

<%= form_for(@comment ,:url => {:action => :new_comment, :controller => :posts} ) do |f| %>

	 <!--hidden field -->
	 <%= hidden_field_tag :post_id, @post.id %>


    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/index.html.erb
<p>Welcome to my page. You can post a photo and we'll give you feedback on ways to improve. </p>

<%= link_to "view recent posts", posts_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>